### ISSUE TITLE
CANNOT LINK EXECUTABLE: library "libcrypto.so.3" not found

### ISSUE THREAD

**Issue by gokyuzugokturk** [Darktron/pre-compiled#1]
CPU: MediaTek MT6753, Core: 8 x ARM Cortex-A53 @ 1300MHz, 64-bit ARMv8-A
RAM: 3GB, Depolama: 16GB, Android 7

I did everything for my first phone. It works well !

*****

CPU: MediaTek Helio P10 (MT6755M), Core: 4 x ARM Cortex-A53 @ 1807MHz + 4 x ARM Cortex-A53 1807MHz, 64-bit ARMv8-A
RAM: 4GB, Depolama: 64GB, Android 6

I did everything for my second phone. It gives error:

WARNING: linker: /data/data/com.termux/files/home/ccminer/ccminer: unused DT entry: type 0x1d arg 0x616
WARNING: linker: /data/data/com.termux/files/home/ccminer/ccminer: unsupported flags DT_FLAGS_1=0x8000001
CANNOT LINK EXECUTABLE: library "libcrypto.so.3" not found
page record for 0x7f9b278010 was not found (block_size=16)

I installed the correct termux for the Android version.
What should I do to fix the error ?

**Comment by Darktron** [comment]
Try
`pkg update`
Then
`pkg upgrade`
Then
`pkg install openssl`

**Comment by gokyuzugokturk** [comment]
I did them but not helped.
any different advise pls ?

**Comment by gokyuzugokturk** [comment]
$ pkg update
Hit:1 https://packages-cf.termux.dev/apt/termux-main-21 stable InRelease
Hit:2 https://termux.dev/game-packages-21-bin games InRelease
Hit:3 https://termux.dev/science-packages-21-bin science InRelease
Reading package lists... Done
Building dependency tree                        Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree
Reading state information... Done               Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
$

***********

$ pkg upgrade
Hit:1 https://termux.dev/game-packages-21-bin games InRelease
Hit:2 https://termux.dev/science-packages-21-bin science InRelease
Hit:3 https://packages-cf.termux.dev/apt/termux-main-21 stable InRelease
Reading package lists... Done
Building dependency tree                        Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree
Reading state information... Done               Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
$

***********

$ pkg install openssl
Reading package lists... Done                   Building dependency tree
Reading state information... Done               openssl is already the newest version (1.1.1d-2).                                               0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
$

***********

$ pkg show openssl
Package: openssl
Version: 1.1.1d-2
Maintainer: Fredrik Fornwall @fornwall
Installed-Size: 4284 kB
Depends: ca-certificates
Conflicts: libcurl (<< 7.61.0-1)
Breaks: openssl-tool (<< 1.1.1b-1), openssl-dev
Replaces: openssl-tool (<< 1.1.1b-1), openssl-dev
Homepage: https://www.openssl.org/
Download-Size: 1143 kB
APT-Manual-Installed: yes
APT-Sources: https://packages-cf.termux.dev/apt/termux-main-21 stable/main aarch64 Packages
Description: Library implementing the SSL and TLS protocols as well as general purpose cryptography functions
$

***********

$ cd ccminer
$ ls
ccminer  config.json  start.sh
$ ./start.sh
WARNING: linker: /data/data/com.termux/files/home/ccminer/ccminer: unused DT entry: type 0x1d arg 0x616                                         WARNING: linker: /data/data/com.termux/files/home/ccminer/ccminer: unsupported flags DT_FLAGS_1=0x8000001
CANNOT LINK EXECUTABLE: library "libcrypto.so.3" not found
page record for 0x7f99360010 was not found (block_size=16)
$

This the results.

**Comment by Darktron** [comment]
Which branch did you use "generic"?
Can you provide results of `lscpu`

**Comment by gokyuzugokturk** [comment]
I tried "generic" and "a53". both are the same result.

aida64:
CPU: MediaTek Helio P10 (MT6755M)
Core: 4 x ARM Cortex-A53 @ 1807MHz + 4 x ARM Cortex-A53 1807MHz
64-bit ARMv8-A

lscpu:
aarch64
32-bit, 64-bit
ARM
Cortex-A53

**Comment by Darktron** [comment]
Seems we have mismatch openssl packages have you tried starting from scratch again. I use termux v0.118.0
![Screenshot_20240805_082642_Termux](https://github.com/user-attachments/assets/a929dcc7-a62d-48d1-bb39-06d728aa3072)
![Screenshot_20240805_082607_Termux](https://github.com/user-attachments/assets/3aa8f57b-40dd-4e6f-bb9c-a1f08bb9e6b9)

**Comment by gokyuzugokturk** [comment]
I tried 14 times. but not helped. You have openssl v1.3.3.1 as I see. My phone has openssl v1.1.1d-2
I think this is the problem. is there any way to upgrade it except pkg update & pkg upgrade & pkg install openssl ?

$ pkg show openssl
Package: openssl
Version: 1.1.1d-2
Maintainer: Fredrik Fornwall @fornwall
Installed-Size: 4284 kB
Depends: ca-certificates
Conflicts: libcurl (<< 7.61.0-1)
Breaks: openssl-tool (<< 1.1.1b-1), openssl-dev
Replaces: openssl-tool (<< 1.1.1b-1), openssl-dev
Homepage: https://www.openssl.org/
Download-Size: 1143 kB
APT-Manual-Installed: yes
APT-Sources: https://packages-cf.termux.dev/apt/termux-main-21 stable/main aarch64 Packages
Description: Library implementing the SSL and TLS protocols as well as general purpose cryptography functions
$

**Comment by Darktron** [comment]
You can try changing repo within termux `termux-change-repo` see if you could find the 1:3.3.1 if not I'll build you a custom one

**Comment by gokyuzugokturk** [comment]
termux-app_v0.118.0+github-debug_arm64-v8a.apk and earlier versions cannot be installed to the phone. The phone has Android 6. So, I installed "https://github.com/termux/termux-app/releases/download/v0.119.0-beta.1/termux-app_v0.119.0-beta.1+apt-android-5-github-debug_arm64-v8a.apk" for  Android 5 and 6 only.

I didnt find any solution to install openssl v1:3:3:1

$ termux-change-repo
termux-change-repo: command not found

Thanks for your help.

**Comment by Darktron** [comment]
Thank you, working on it with this beta release. Lets see what i can do

**Comment by R75880** [comment]
You must use another code. This code battle is for my device.

**Comment by Darktron** [comment]
I tried to compile in this termux v0.119.0-beta.1 version for android 5 and 6 and i was unsuccessful there are some dependencies missing including above mentioned in this issue. I suggest giving verusminer apk a try [https://pangz-lab.github.io/verusminer/](url) if that doesn't work then can try userland method [https://github.com/Oink70/Android-Mining](url)

**Comment by gokyuzugokturk** [comment]
Thanks for trying to help me. I will try the other options.

**Comment by gokyuzugokturk** [comment]
UPDATE for your information:

Your script works with termux v0.119.0-beta Android 7+ perfectly.
Video: https://www.youtube.com/watch?v=zRPAgmRYf_0
Video: https://www.youtube.com/watch?v=NOYtrI_XSk0

Your script doesnt work with termux v0.119.0-beta Android 5 & 6
In my case, termux v0.118 cannot be installed into the phone. So, I couldnt test your script with termux v0.118
UserLand works but the mining progress not starting at the same phone. 
I tested UserLand in another phone:  The mining works well.
Verus Miner works well in the same phone. So, I will use Verus Miner for this phone.

Best Regards.
