### ISSUE TITLE
Can you write a tutorial for compiling

### ISSUE THREAD

**Issue by qimeila** [Darktron/pre-compiled#3]
Thanks for sharing, I would like to compile my own ccminer to run on termux, which source code did you use? Is it possible to write a compilation script?

**Comment by qimeila** [comment]
and how to optimize for 4*A72+4*A53 cpu？i try to set mtune=cortex-a72,cortex-a53 or mtune=cortex-a72,cortex-a72.cortex-a53 
but get error

**Comment by Darktron** [comment]
First question: [https://github.com/Darktron/ccminer](url) for source you can compile yourself if you'd like.
Second question: I already have a cortex-a72 + cortex-a53 in this repository look at the branches.
Third question: well you will need to learn a bit about clang to know what flags to use.
